spring:
  application:
    name: common-libraries
  profiles:
    active: default
  main:
    banner-mode: off

logging:
  level:
    root: INFO
    com.grace.recon: INFO
  file:
    name: logs/${spring.application.name}.log
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } --- [%t] %-40.40logger{39}: %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"

# Placeholder for common properties
common:
  version: 1.0.0
  feature-flags:
    example-feature-enabled: true
  security:
    jwt-secret: placeholder-jwt-secret-change-in-prod
    aes-gcm-key: placeholder-aes-gcm-key-change-in-prod
